language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t nomad20/react_fib -f ./client/Dockerfile.dev  ./client
script:
  - docker run CI=true nomad20/react_fib npm test
after_success:
  - docker build -t nomad20/multi-client ./client
  - docker build - t nomad20/multi-nginx ./nginx
  - docker build - t nomad20/multi-server ./server
  - docker build - t nomad20/multi-worker ./worker
  - >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - docker push nomad20/multi-client
  - docker push nomad20/multi-nginx
  - docker push nomad20/multi-server
  - docker push nomad20/multi-worker