version: "3.3"
services:
    nginx:
        depends_on: 
            - node-server
            - client
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - '3050:80'
    postgres:
        image: "postgres:latest"
        hostname: postgres
        environment: 
            - POSTGRES_PASSWORD=postgres_password
        restart: always
    redis:
        image: "redis"
    node-server:
        build:
            dockerfile: Dockerfile
            context: ./server
        depends_on: 
            - postgres
            - redis
        volumes: 
            - /usr/src/app/node_modules
            - ./server:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - /usr/src/app/node_modules
            - ./client:/usr/src/app
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
    worker:
        build:
            dockerfile: Dockerfile
            context: ./worker
        volumes: 
            - /usr/src/app/node_modules
            - ./worker:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379